---
title: "Morning Activity"
author: "Connor Flynn"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(kableExtra)

```
```{r}
crabs <- read_csv(here("data", "HTL-MAR-FiddlerCrabBodySize.csv"))
```

#ggplot 
```{r, "There is a positive linear correlation between latitude and fiddler crab carapace width."}
ggplot(data = crabs, aes(x = Latitude, y = carapace_width)) +
  geom_point()+
  labs(
    x = "latitude",
    y = "carapace width (mm)",
    title = "Fiddler Crab Carapace Width Verus Latitude"
  ) +
  theme(plot.title = element_text(hjust = 0.5))
```



##### Fiddler crab carapace width (mm) verus latitude from July to August, 2016. 


```{r}
crabs_1 <- crabs %>% 
  group_by(Site) %>% 
  summarise(
    mean_carapace = round(mean(carapace_width), 2),
    sd_carapace = round(sd(carapace_width), 2),
    sample_size = n()
  )


crabs_1 %>% 
  kable(col.names = c("Site", "Mean Carapace", "Standard Deviation Carapace", 
                      "Sample Size")) %>% 
  kable_paper(full_width = FALSE)
```


```{r, "As the mean annual water temperature increases, the carapace width decreases."}
ggplot(data = crabs, aes(x = MATW, y = carapace_width)) +
  geom_point() +
  labs(
    x = "Mean Annual Water Temperature (Celcius)",
    y = "Carapace Width (mm)",
    title = "Fiddler Crab Carapace Width Versus Mean Annual Water Temperature"
  ) +
  theme(plot.title = element_text(hjust = 0.5))




```

#### Fiddler crab carapace width versus mean annual water temperature. 










